parameters:
    synergy.grants.actions:
        read: false
        create: false
        update: false
        delete: false
    synergy.grants.entity: {}
#        exampleEntity:
#            read: true

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    Efrogg\Synergy\:
        resource: '../../'

    Efrogg\Synergy\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Efrogg\Synergy\Helper\EntityHelper:
        calls:
            - [setEntities, [!tagged_iterator synergy.entity]]

    Efrogg\Synergy\Acl\AclManager:
        calls:
            - [ setDefaultActionGrants , [ '%synergy.grants.actions%' ]]
            - [ setDefaultEntityGrants , [ '%synergy.grants.entity%']]

    Efrogg\Synergy\Mercure\Collector\ActionCollectorInterface:
        class: Efrogg\Synergy\Mercure\Collector\ActionCollector

    redis_persister:
        class: Redis
        factory: 'Efrogg\Synergy\AutoSync\RedisAdapter::createConnection'
        arguments:
            - '%env(REDIS_HOST)%'
            - '%env(REDIS_PORT)%'
            - '%env(REDIS_DB)%'

    Efrogg\Synergy\AutoSync\Persister\AutoSyncPersisterInterface:
        class: Efrogg\Synergy\AutoSync\Persister\NullPersister
